# Site settings
title: Paz Aricha
email: paz@pazaricha.com
description: The online home of Paz Aricha
baseurl: ""
url: "http://www.pazaricha.com"

author:
  name     : 'Paz Aricha'
  email    : paz@pazaricha.com
  url      : http://www.pazaricha.com
  facebook : http://facebook.com/bluzgraphics
  twitter  : http://twitter.com/bluzthemes
  github   : https://github.com/pazaricha

github: https://github.com/pazaricha
disqus_shortname: "pazaricha"
google_analytics: UA-31386532-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/

